#############################################################################
# Makefile for building: CPP_Project
# Generated by qmake (3.1) (Qt 5.12.8)
# Project:  CPP_Project.pro
# Template: app
# Command: /Users/maximeolivie/Qt/5.12.8/clang_64/bin/qmake -o Makefile CPP_Project.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.14 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.14 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/macx-clang
QMAKE         = /Users/maximeolivie/Qt/5.12.8/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/maximeolivie/Qt/5.12.8/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/maximeolivie/Qt/5.12.8/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = CPP_Project1.0.0
DISTDIR = /Users/maximeolivie/Documents/Licence_informatique/M1/CPP/TP/TP1/projet/obj/CPP_Project1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.14 -Wl,-rpath,@executable_path/../Frameworks
LIBS          = $(SUBLIBS)    
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = expr.cpp \
		main.cpp \
		binaryop.cpp \
		exprlexer.cpp \
		exprparser.cpp \
		syntaxerror.cpp \
		token.cpp \
		value.cpp 
OBJECTS       = obj/expr.o \
		obj/main.o \
		obj/binaryop.o \
		obj/exprlexer.o \
		obj/exprparser.o \
		obj/syntaxerror.o \
		obj/token.o \
		obj/value.o
DIST          = /Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/spec_pre.prf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/qdevice.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/device_config.prf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/common/unix.conf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/common/mac.conf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/common/macx.conf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/common/sanitize.conf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/common/gcc-base.conf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/common/clang.conf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/common/clang-mac.conf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/qconfig.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/qt_functions.prf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/qt_config.prf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/macx-clang/qmake.conf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/toolchain.prf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/mac/toolchain.prf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/default_pre.prf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/mac/default_pre.prf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/resolve_config.prf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/default_post.prf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/qml_debug.prf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/mac/mac.prf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/warn_on.prf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/qmake_use.prf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/file_copies.prf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/mac/rez.prf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/exceptions.prf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/yacc.prf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/lex.prf \
		CPP_Project.pro binaryop.hpp \
		expr.hpp \
		exprlexer.hpp \
		exprparser.hpp \
		syntaxerror.hpp \
		token.hpp \
		typealiases.hpp \
		value.hpp expr.cpp \
		main.cpp \
		binaryop.cpp \
		exprlexer.cpp \
		exprparser.cpp \
		syntaxerror.cpp \
		token.cpp \
		value.cpp
QMAKE_TARGET  = CPP_Project
DESTDIR       = 
TARGET        = CPP_Project

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 10.15
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/maximeolivie/Documents/Licence_informatique/M1/CPP/TP/TP1/projet/CPP_Project.pro


include /Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

CPP_Project:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: CPP_Project.pro /Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/macx-clang/qmake.conf /Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/spec_pre.prf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/qdevice.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/device_config.prf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/common/unix.conf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/common/mac.conf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/common/macx.conf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/common/sanitize.conf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/common/gcc-base.conf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/common/clang.conf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/common/clang-mac.conf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/qconfig.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/qt_functions.prf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/qt_config.prf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/macx-clang/qmake.conf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/toolchain.prf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/mac/toolchain.prf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/default_pre.prf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/mac/default_pre.prf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/resolve_config.prf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/default_post.prf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/qml_debug.prf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/mac/mac.prf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/warn_on.prf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/qmake_use.prf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/file_copies.prf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/mac/rez.prf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/exceptions.prf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/yacc.prf \
		/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/lex.prf \
		CPP_Project.pro
	$(QMAKE) -o Makefile CPP_Project.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/spec_pre.prf:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/qdevice.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/device_config.prf:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/common/unix.conf:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/common/mac.conf:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/common/macx.conf:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/common/sanitize.conf:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/common/gcc-base.conf:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/common/gcc-base-mac.conf:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/common/clang.conf:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/common/clang-mac.conf:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/qconfig.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3drender.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_core.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_dbus.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_help.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_location.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_location_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_network.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_positioningquick.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_repparser.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_scxml.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_service_support_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_webengine.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_websockets.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_webview.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/qt_functions.prf:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/qt_config.prf:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/macx-clang/qmake.conf:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/exclusive_builds.prf:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/mac/sdk.prf:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/toolchain.prf:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/mac/toolchain.prf:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/default_pre.prf:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/mac/default_pre.prf:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/resolve_config.prf:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/default_post.prf:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/mac/default_post.prf:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/mac/objective_c.prf:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/qml_debug.prf:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/mac/mac.prf:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/warn_on.prf:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/qmake_use.prf:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/file_copies.prf:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/mac/rez.prf:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/mac/asset_catalogs.prf:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/testcase_targets.prf:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/exceptions.prf:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/yacc.prf:
/Users/maximeolivie/Qt/5.12.8/clang_64/mkspecs/features/lex.prf:
CPP_Project.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile CPP_Project.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile CPP_Project

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)" -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

check: first

benchmark: first

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

obj/expr.o: expr.cpp exprlexer.hpp \
		token.hpp \
		expr.hpp \
		exprparser.hpp \
		value.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/expr.o expr.cpp

obj/main.o: main.cpp value.hpp \
		token.hpp \
		binaryop.hpp \
		exprlexer.hpp \
		exprparser.hpp \
		expr.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o main.cpp

obj/binaryop.o: binaryop.cpp binaryop.hpp \
		token.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/binaryop.o binaryop.cpp

obj/exprlexer.o: exprlexer.cpp exprlexer.hpp \
		token.hpp \
		value.hpp \
		binaryop.hpp \
		syntaxerror.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/exprlexer.o exprlexer.cpp

obj/exprparser.o: exprparser.cpp exprparser.hpp \
		token.hpp \
		binaryop.hpp \
		typealiases.hpp \
		value.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/exprparser.o exprparser.cpp

obj/syntaxerror.o: syntaxerror.cpp syntaxerror.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/syntaxerror.o syntaxerror.cpp

obj/token.o: token.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/token.o token.cpp

obj/value.o: value.cpp value.hpp \
		token.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/value.o value.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

